version: '3.9'
services:
  app:
    image: ghcr.io/algostract/unfiles:latest
    env_file:
      - .env
    volumes:
      - unfiles_data:/app/.data
    expose:
      - 3000
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  unfiles_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/unfiles/.data

networks:
  internal:
    driver: overlay
